### ISSUE TITLE
Doesn't work on wordpress 3.5

### ISSUE THREAD

**Issue by cfdev** [WPsites/Resize-images-before-upload#1]
Hi,
Many thanks for this plugin!!! 

But with the new media manager of wordpress 3.5, your plugin doesn't work :( ...

**Comment by WPsites** [comment]
Hmmm, thought I checked that on the beta and it worked ok. I will look into it.

**Comment by cfdev** [comment]
There is an way what works!
see attached files

resize_way_ok:
![resize_way_ok](https://f.cloud.github.com/assets/1363334/13018/7e770e94-45d9-11e2-9444-31a1325e5c9a.png)

resize_way_NOT:
![resize_way_NOT](https://f.cloud.github.com/assets/1363334/13019/85973276-45d9-11e2-832b-2a6d7eb2e1c1.png)

**Comment by timbunch** [comment]
Likewise, IE+Flash don't play well with it in WP3.5. No complaints in Chrome, that I saw.

**Comment by cfdev** [comment]
I have Firefox v17.0.1

**Comment by WPsites** [comment]
There was no problem with the media page as it hasn't changed much. It was the media manager when editing a post/page that works in a totally different way.

I fixed that problem but had to remove the tick box for enable/disable. So now if the plugin is installed and enabled it's going to try and resize your images. If you don't want this then just disable the plugin.

The switch to Flash on incompatible browsers doesn't seem to work too good on the new media manager so there is still work to be done but it should now work for more of you as long as you either have a HTML5 browser or you use the media section rather than upload images from the post/page edit screen.

**Comment by cfdev** [comment]
| There was no problem with the media page as it hasn't changed much.
Yes always work for me.

| It was the media manager when editing a post/page that works in a totally different way.
| I fixed that problem
Failed for me :( with v0.7

**Comment by WPsites** [comment]
I've just tried it in Firefox 5, IE 8, Chrome and Safari without problems so not sure what's going wrong there.

**Comment by dvanoss** [comment]
When I updated to version 0.8 I get a "Fatal error: Call to undefined function wp_max_upload_size() in /home/xxxxxxx/public_html/main/wp-content/plugins/resize-images-before-upload/resize-images-before-upload.php on line 28".  I have to delete the plugin via FTP in order to have access to my site again. I'm using Wordpress 3.4.2 (3.5 causes problems with my Admin).

**Comment by WPsites** [comment]
hmm..  wp_max_upload_size() has been around since 2.5.0

**Comment by WPsites** [comment]
dvanoss: a new version is being uploaded right now that checks the wp_max_upload_size() function is defined, if not then the value is just taken from ini_get('upload_max_filesize'). Should solve your problem.

**Comment by dvanoss** [comment]
Excellent - that did the trick.

**Comment by DanOpcode** [comment]
I'm running Wordpress 3.5 and 0.9 of this plugin, and I'm also experiencing problems. I have the exact same problem as this guy: http://wordpress.org/support/topic/does-not-workfor-some-reason

**Comment by cfdev** [comment]
http://wordpress.org/support/topic/does-not-workfor-some-reason
+1
try with this image: http://upload.wikimedia.org/wikipedia/commons/a/a2/Polycyclic_Aromatic_Hydrocarbons_In_Space.jpg

**Comment by WPsites** [comment]
I've just pushed a new version up to the WordPress repository that should hopefully solve your problems. Let me know if that's not the case.

**Comment by DanOpcode** [comment]
Nope, doesn't work with the _new_ media uploader.

**Comment by WPsites** [comment]
MaTachi: what browser are you using? Has it got Flash installed? (flash is only needed for browsers that don't do HTML5 too well)

Have you been shown the alert that says Flash is needed? 

Does the media section allow you to upload or is that broken as well as manage media from within a post/page?

Thanks for your feedback. Hopefully this issues will be sorted soon.

**Comment by DanOpcode** [comment]
Firefox 17 and I have Flash installed. No alerts regarding missing Flash.

I recorded a video of the problem: http://youtu.be/oTRAWUxziCY As you can see is the first image I upload through the old media uploader resized to width 570, while the second image that I upload through the new media uploader in a post isn't resized.

**Comment by WPsites** [comment]
Firefox 17 should be compatible and won't need the Flash runtime, which is why you won't have seen that alert.

I updated my version of Firefox (not to 17 though, it only allowed me to upgrade to 12) and at first few times I tried I also had the same problem as you. But then I edited the plugin file and because I had a syntax error in the code WP disabled the plugin; I then reverted back to the old version and enabled the plugin and then upload worked fine, resizing the images!?

I'm thinking something somewhere is getting cached, maybe an option or something and maybe the act of disabling and re-enabling the plugin is clearing this or something.

Can you try making sure your browser cache is clear, and nothing else is being cached and then disable/re-enable the plugin and see if that helps.

Otherwise I really am stuck here.. It seems pretty much impossible to debug exactly what Plupload is doing in the background.

**Comment by DanOpcode** [comment]
I cleared the browser cache, disabled and enabled the plugin, uploaded an image and it wasn't resized.

**Comment by WPsites** [comment]
OK. Others seem to be still experiencing problems. I'm going to have to look into it further.

**Comment by jayharle** [comment]
I'm reporting the same exact issue as well as shown in MaTachi 's video.

**Comment by WPsites** [comment]
Hopefully I've managed to fix this in version 1.2 which I've just uploaded.

Please let me know.

**Comment by DanOpcode** [comment]
I updated the plugin to 1.2 and WordPress to 3.5.1, and it seems to work now. I haven't done any extensive testing tho, only with 3 images. Thank you very much!

**Comment by jayharle** [comment]
I tested this last night and all appears to be well for me. Thanks!!

**Comment by cfdev** [comment]
it working !! Many thanks ! :)
